"""Stage: file filter (criterion C6).

Drops files that must not go to analysis (README/.gitignore/images/lockfiles/
binary/generated/oversized), routes dependency manifests to SCA, keeps real code
for the deterministic + LLM stages. Every drop is recorded with a reason
(result.files_skipped + metric + log) so it is visible in the summary.
"""

from __future__ import annotations

import fnmatch

from aegis.config import get_config
from aegis.obs import get_logger, metrics
from aegis.pipeline.state import PipelineState
from aegis.providers.diffparse import language_of
from aegis.schemas import FileChange

log = get_logger("aegis.filter")

_GENERATED_MARKERS = ("@generated", "do not edit", "code generated by")


def _matches_any(path: str, globs: list[str]) -> str | None:
    low = path.lower()
    for g in globs:
        if fnmatch.fnmatch(low, g.lower()):
            return g
    return None


def _added_bytes(fc: FileChange) -> int:
    return sum(len(ln.content) + 1 for h in fc.hunks for ln in h.lines)


def _looks_generated(fc: FileChange) -> bool:
    head = "\n".join(
        ln.content for h in fc.hunks for ln in h.lines[:5]
    ).lower()
    return any(m in head for m in _GENERATED_MARKERS)


async def apply_filter(state: PipelineState) -> None:
    cfg = get_config().filter
    ignore = list(cfg.ignore_globs) + list(state.ctx.ignore_globs)
    manifests = cfg.sca_manifests

    kept: list[FileChange] = []
    skipped: list[dict[str, str]] = []

    for fc in state.files:
        path = fc.path

        if fc.status == "deleted":
            skipped.append({"path": path, "reason": "deleted"})
            continue

        man = _matches_any(path, manifests)
        if man:
            # Not code — handed to SCA (Phase 3), not the LLM.
            state.manifest_files.append(fc)
            skipped.append({"path": path, "reason": "manifest->sca"})
            continue

        if fc.is_binary:
            skipped.append({"path": path, "reason": "binary"})
            continue

        ig = _matches_any(path, ignore)
        if ig:
            skipped.append({"path": path, "reason": f"ignored:{ig}"})
            continue

        if language_of(path) is None:
            skipped.append({"path": path, "reason": "non-code"})
            continue

        if _added_bytes(fc) > cfg.max_file_bytes:
            skipped.append({"path": path, "reason": "too-large"})
            continue

        if _looks_generated(fc):
            skipped.append({"path": path, "reason": "generated"})
            continue

        kept.append(fc)

    state.code_files = kept
    state.result.files_scanned = [f.path for f in kept]
    state.result.files_skipped = skipped
    for s in skipped:
        metrics.filter_skipped_total.labels(s["reason"].split(":")[0]).inc()

    log.info(
        "filter.applied", scan_id=state.scan_id,
        kept=len(kept), skipped=len(skipped),
        manifests=len(state.manifest_files),
        skipped_detail=skipped[:50],
    )
